---
title: "Final Project"
name: "Makayla Ashe"
date: "12/16/19"
output:
  html_document:
    df_print: paged
  fig_width: 10
  fig_height: 6
  html_notebook: null

---
I'm examining what variables are cofounding with poverty in the United States. Specifically, what is the relationship between poverty and minority population?  

## Front Matter
```{r}
# clean up workspace environment
rm(list = ls())

# all packages used for the assignment
library(mosaic)
library(tidyverse)
library(manipulate)
library(ggplot2)
library(readxl)
library(devtools)
library(leaflet)
library(usmap)
library(ggplot2)
library(dplyr)
library(party)
```


## Gathering Data Set 1
```{r}
library(readxl)
fooddata <- read_excel("~/Desktop/fooddata1.xlsx")
head(fooddata)
```

##Gathering Data Set 2
```{r}
mapdata<-
((usmap::us_map(regions="counties")))
head(mapdata)
```

## Cleaning Data Part 1
```{r}
#renaming and mutating
fooddata <-
  fooddata %>%
  filter(row_number() > 1)%>%
  rename(state = "State", 
         county = "County", 
         pop = 'POP2010',
         housingunits = 'OHU2010',
         lowinc = "TractLOWI",
    novehicle = 'TractHUNV',
         SNAP = 'TractSNAP')%>%
  mutate(novehicle=(novehicle/pop)*100, SNAP=(SNAP/pop)*100, lowinc=(lowinc/pop)*100, minoritypop=((TractBlack+TractAsian+TractNHOPI+TractAIAN+TractOMultir+TractHispanic)/pop)*100)
head(fooddata)
```


##Variable Selection
```{r}
#selecting
fooddata <-
  fooddata %>%
    group_by(county)%>%
  filter(row_number() > 1)%>%
  select(state, county, pop, housingunits, minoritypop, Urban, PovertyRate, MedianFamilyIncome, novehicle, SNAP, lowinc)
head(fooddata)
```

##Cleaning Data Set #2
```{r}
regex <- ".*([County])$"
mapdata<-
mapdata %>% 
  filter(grepl(pattern = regex, county)) %>% 
  mutate(county = gsub(pattern = " County", replacement = "", county))%>%
  rename(state="full")
```



##Joining
```{r}
joined<-
  fooddata%>%
  left_join(mapdata)
  head(joined)
```


##Graphing
```{r}
#GRAPH1

probability1<-
  fooddata%>%
  select(pop, housingunits, Urban, PovertyRate, MedianFamilyIncome, novehicle, lowinc, SNAP, minoritypop)%>%
  na.omit()

mod1<- party::ctree(PovertyRate~Urban+minoritypop, data=fooddata)
plot(mod1, type="simple")
```



```{r}
#GRAPH2
fooddata %>%
  group_by(county) %>%
  filter(PovertyRate > 18)%>%
  ggplot(aes(x=minoritypop, y=SNAP, color=as.character(Urban))) + 
 geom_line(alpha=.5) + 
  xlim(0,100)+
  ylim(0,100)
```


```{r}
#GRAPH4
fooddata %>%
  group_by(county) %>%
  filter(minoritypop<50)%>%
  ggplot(aes(x=MedianFamilyIncome)) + 
  geom_density()+
  geom_density(data=fooddata, fill="blue", alpha=.25)+
  facet_wrap(~Urban)+
  xlim(0,180000)
```

```{r}
Map<-
joined%>%
  ggplot()+
  geom_polygon(data=joined,aes(fill= poverty, x=x, y=y))+
  theme_void()+
  coord_map()
View(Map)
```
